entando/app-builder

src/ui/widgets/config/WidgetConfigForm.js, src/ui/widgets/config/forms/InternalServletConfigForm.js, test/test/mocks/widgets.js, test/ui/widgets/config/WidgetConfigForm.test.js, test/ui/widgets/config/forms/InternalServletConfigForm.test.js, test/ui/widgets/list/WidgetListTable.test.js
To be merged **before** the following PR: https://github.com/entando/entando-components/pull/239
Force plugin forms to wrap the forms with reduxForm themselves, in order to allow them to modify the config object before submit
=> Allow plugin forms them to modify the config object before submit

src/ui/fragments/list/FragmentListTable.js
Hi @nicpuddu @alessioscalici @mcarta-rt @fedelocci ,
column name renamed to code in the fragment's table.
Thanks!
=> EN-1472-ux-patterns-fragments-column-code-missing

src/ui/common/form/EditAttributeForm.js, src/ui/pages/common/PageForm.js
Code readonly for profile type attributes in edit mode and removed comment in PageForm
=> [5.0.1] EN-1584-501-profiles-types-edit-attribute-code-not-editable

src/ui/common/form/EditAttributeForm.js, src/ui/pages/common/PageForm.js
Code readonly for profile type attributes in edit mode and removed comment in PageForm
=> EN-1584-profiles-types-edit-attribute-code-not-editable

sass/pages/config/PageConfigPage.scss, src/ui/pages/config/PageConfigPage.js
all the top toolbar buttons are now transparent based on figma. bottom buttons are now in a sticky toolbar right at the bottom.
=> EN-2282 - amend toolbar buttons in Page Configuration

sass/pages/config/PageConfigPage.scss
Sorry on finding this late. I found a bug when toolbar is in fixed/sticky mode, toolbar scrolling does not work. This was overlapped with another 'dummy' element thus making scroll wheel not working.
=> EN-2309 - page config toolbar scroll fix when it is in sticky mode

src/api/dataTypes.js, test/api/dataTypes.test.js
When running app-builder with mocked data, dataTypes fail to get loaded due to the mismatch of response shape in the mock.
=> get dataTypes mock: mock payload instead of full response

sass/internal-page/InternalPage.scss
The fix is just by overriding the Patternfly style for active menu items in a persistent secondary navbar. It seems that they didn't consider a mix of multi-level menu items and single-level ones as the corresponding style appears to be only suitable for multi-level items.
=> EN6-92 Fix menu height issue

src/ui/users/my-profile/PasswordFormContainer.js
It was the 'pure' option in redux connect function that causes the page to go haywire - infinite loops of checks of state values most especially the `matchElement` validation that is found on `newPasswordConfirm`. If there's a matchElement validation, better avoid turning on `pure` option.
=> EN6-147 my profile page fix

src/ui/internal-page/InternalPage.js
Remove the unused grid button, which is located at the top-right corner of the page.
=> EN6-148 Remove unused AdminAppSwitch

src/ui/users/list/UserSearchFormContainer.js
prop 'onWillMount' attempts to invoke but not found on user list. this only happens when it is integrated with entando app such as CMS
=> EN6-172 dispatch prop onWillMount not found error fix

src/state/digital-exchange/components/actions.js, src/ui/digital-exchange/components/list/ComponentListContainer.js, src/ui/pages/config/PageConfigPage.js
This commit includes spinner activation and no-scroll issue resolve.
1. Spinner activation was accessing the spinner status incorrectly from the state. Also, toggleLoading was never called when there are no Digital Exchanges available, as API is returning 304 code without any JSON, so frontend fetching PROMISE outputs error (no JSON returned) instead of resolving. That's why I put toggleLoading in error too.
2. I tested while no-scroll removed and all worked like a charm and smoothly. So, I think this way is better.
=> ENG-7 Activate a spinner while in loading state

src/state/digital-exchange/components/actions.js, src/ui/digital-exchange/components/common/ComponentInstallActions.js, src/ui/digital-exchange/components/common/ComponentInstallActionsContainer.js, test/state/digital-exchange/components/actions.test.js, test/ui/digital-exchange/components/common/ComponentInstallActionsContainer.test.js
After clicking an install or uninstall button, a spinner will instantaneously be shown to provide immediate feedback to the user prior to the actual start of the installation/uninstallation of a DE component.
=> ENG-29 DE Component Install/Uninstall Button Feedback

src/ui/widgets/config/WidgetConfigPage.js
Currently `ROUTE_PAGE_CONFIG` is equal to: '/page/configuration/:pageCode' .
`react-router-dom`s `Link` component does not accept `params` prop. Although, `:pageCode` is being used at different places.
=> ENG-78 make breadcrumb Link dynamic

src/state/login-form/actions.js
`login` function responds with 401 unauthorized error from API, which does not go to `then` but to `catch`, where we did not have any logic to handle it, due to it UX was not indicating any error and the user thought he was stuck on the page and screen was `frozen`.
=> ENG-36 catch unathorized error

src/locales/it.js
use "tipo di widget" to translate "widget type" as it was already used that way
=> EN-59 other i18n fixes

src/locales/en.js, src/locales/it.js, src/locales/pt.js, src/ui/digital-exchange/components/common/ComponentInstallActions.js, src/ui/digital-exchange/components/common/ComponentInstallActionsContainer.js, src/ui/digital-exchange/components/common/ConfirmUninstallModal.js
Implements confirmation modal shown on the uninstall of a digital exchange component.
=> ENG-387 Add ConfirmUninstallModal to ComponentInstallActions

package-lock.json, package.json, sass/pages/common/PageTree.scss, sass/pages/config/ContentPages.scss, src/state/pages/actions.js, src/state/pages/reducer.js, src/state/pages/types.js, src/ui/pages/common/PageTree.js, src/ui/pages/common/PageTreeContainer.js, src/ui/pages/common/PageTreeSelectorContainer.js, src/ui/pages/config/ContentPages.js, src/ui/pages/config/ContentPagesContainer.js, test/state/pages/actions.test.js, test/state/pages/reducer.test.js, test/ui/pages/common/PageTreeSelectorContainer.test.js, test/ui/pages/config/ContentPageContainer.test.js
- This PR is markes as `draft` because once `frontend-libraries` has a newer version of `pagetreeselector` its version also needs to be bumped up in `app-builder`.
=> ENG-519 implement app-builder side for expand/collapse all

src/app-init/router.js, src/locales/en.js, src/locales/it.js, src/locales/pt.js, src/state/page-config/selectors.js, src/state/widgets/actions.js, src/ui/app/App.js, src/ui/pages/config/DraggableWidgetFrame.js, src/ui/pages/config/DroppableWidgetFrame.js, src/ui/pages/config/PageConfigGridCol.js, src/ui/pages/config/WidgetFrame.js, src/ui/widgets/clone/CloneWidgetFormContainer.js, src/ui/widgets/clone/CloneWidgetPage.js, src/ui/widgets/common/WidgetForm.js, test/ui/pages/config/WidgetFrame.test.js
This PR implement AdminConsole analogue of cloning a widget. (This PR uses ConfigSimpleParameter approach always, as seen in AdminConsole, although in the second subtask of ENG-722 native config screen will be shown for widgets that have their own unique edit screens, that's why `src/ui/widgets/clone/CloneWidgetFormContainer.js` line 49 has that empty `if` block)
=> ENG-722 implement clone widget with ConfigSimpleParam

src/ui/widgets/clone/CloneWidgetFormContainer.js
This requirement is missed from recent updates: 
"Save As" creates an in memory, client-side copy of the widget, where the main widget data:
- Code
- Title(s)
- Group
is cleared but the:
- Parameters
are preserved.
So, this PR is the implementation
=> ENG-722 removing parent widget values on widget form fields

package.json, src/locales/en.js, src/locales/it.js, src/locales/pt.js, src/ui/profile-types/attributes/EditFormContainer.js, src/ui/user-profile/common/UserProfileForm.js
In `generatetValidatorFunc` I use `this` to save functions, because if we do not "pre-compute" and "cache" the validator functions like `minLength` etc, and we just put `minLength(20)` into `validate` array as a `Field` prop, we get recursive rendering and maximum tree update depth error. So, that's a must have.
=> ENG-1129 implement FE validations for texts and numbers

src/state/page-config/selectors.js
I guess renaming the component name in entando-plugin-jacms is a no-no so I made a selector function to filter out "Entando CMS" to just "CMS"
=> ENG-1276 avoiding name “Entando CMS” in widget list

sass/internal-page/InternalPage.scss
ideal for use in fixed header/footer/dialogs on different states (nav opened, non-legacy mode, etc). Implemented in fixed heading+breadcrumb in content form as well as the bottom control in content form
=> ENG-1378 CSS rule for starting points (left/top) of content area

src/ui/database/dump/DatabaseDumpTablePage.js
This feature was tested and it was working fine during tests done on [ENG-1418](https://jira.entando.org/browse/ENG-1418) ticket, but for some reason, when the same test was done on [ENG-1356](https://jira.entando.org/browse/ENG-1356), the modal was not being opened.
After testing again locally, I was able to reproduce the issue, and the root cause was an condition I added to prevent the fetch to happen multiple times by comparing the prevProps `dumpData` with the new prop. For some reason, it was working during ENG-1418 tests, but now this condition was never match, so I removed it.
=> ENG-1418: removing wrong condition

src/state/groups/actions.js, src/state/groups/selectors.js, test/state/groups/actions.test.js, test/state/groups/selectors.test.js
Please consider this as a workaround, since this groups fetching logic should be on the backend.
=> ENG-2219 show all groups when adding a new page as admin

package-lock.json, src/ui/pages/list/PageTreePageContainer.js
* Fixes page title not falling back to default language title when non-default language title is empty
=> ENG-2642 Invoke fetchLanguages() in PageTreePageContainer
