entando/app-builder

package-lock.json, src/app-init/locale.js, src/index.js, src/state/locale/actions.js, src/state/locale/reducer.js, src/state/locale/selectors.js, src/state/locale/types.js, src/state/rootReducer.js, src/test/Login/LoginFormContainer.test.js, src/test/state/locale/actions.test.js, src/test/state/locale/selectors.test.js, src/test/ui/locale/IntlProviderContainer.test.js, src/ui/locale/IntlProviderContainer.js, src/ui/login/LoginFormContainer.js
Created language selection integration on designtime-admin-app project.
=> EN-801 language choice

sass/pages/config/ContentWidgetElement.scss, sass/pages/config/ToolbarPageConfig.scss, src/ui/pages/config/ContentWidget.js, src/ui/pages/config/ContentWidgetElement.js
fix CSS for list and grid widget view in side bar (page configuration).
=> EN-880 fix CSS style

src/api/labels.js, src/api/languages.js, src/state/languages/actions.js, src/state/languages/reducer.js, src/state/languages/selectors.js, src/state/languages/types.js, src/state/rootReducer.js, test/api/labels.test.js, test/api/languages.test.js, test/state/languages/actions.test.js, test/state/languages/reducer.test.js, test/state/languages/selectors.test.js, test/test/mocks/labels.js, test/test/mocks/languages.js
In this partial PR there's: 
* Languages APIs
* Labels APIs
* Languages state
=> En 964 - languages state

src/api/groups.js, src/ui/groups/list/GroupListMenuActions.js, test/api/groups.test.js
add link from  kebabMenu list to detail group
=> add link from  kebabMenu list to detail group

__mocks__/api/fragments.js, src/api/fragments.js, src/state/fragments/actions.js, src/state/fragments/reducer.js, src/state/fragments/types.js, src/ui/fragments/list/FragmentListTable.js, src/ui/fragments/list/FragmentListTableContainer.js, test/api/fragments.test.js, test/state/fragments/actions.test.js, test/state/fragments/reducer.test.js, test/ui/fragments/list/FragmentListTableContainer.test.js
Fragment delete not making an API call
=> add API, test , reducer and asction for delete fragment

src/ui/pages/edit/PagesEditFormContainer.js, test/ui/pages/edit/PagesEditFormContainer.test.js
=> fix issue and test

__mocks__/api/users.js, src/api/users.js, src/state/users/actions.js, src/ui/users/add/AddFormContainer.js, src/ui/users/list/UserListTable.js, src/ui/users/list/UserListTableContainer.js, test/api/users.test.js, test/state/users/actions.test.js, test/state/users/reducer.test.js, test/state/users/selectors.test.js, test/test/mocks/users.js, test/ui/users/add/AddFormContainer.test.js, test/ui/users/detail/DetailUserTableContainer.test.js, test/ui/users/list/UserListTable.test.js, test/ui/users/list/UserListTableContainer.test.js
add save user actions and test
=> add save user

src/ui/users/list/UserListMenuActions.js
=> EN-1273 DT: users: edit button does nothing

package-lock.json, sass/dashboard/Cards.scss, src/locales/en.js, src/locales/it.js, src/state/integrations/actions.js, src/state/integrations/reducer.js, src/state/integrations/selectors.js, src/state/integrations/types.js, src/state/rootReducer.js, src/ui/dashboard/DashboardPage.js, src/ui/dashboard/Integrations.js, src/ui/dashboard/IntegrationsContainer.js, src/ui/dashboard/UserManagement.js, src/ui/dashboard/UxPatterns.js, test/state/integrations/actions.test.js, test/state/integrations/reducer.test.js, test/state/integrations/selectors.test.js, test/ui/dashboard/DashboardPage.test.js, test/ui/dashboard/Integrations.test.js, test/ui/dashboard/IntegrationsContainer.test.js
the API itself does not exist that, that is why the fetch is not implemented.
It will be done in a separate PR before closing the actual 1300 ticket.
=> En 1300 integrations

src/ui/groups/list/ListGroupPage.js, src/ui/roles/list/ListRolePage.js, src/ui/users/add/AddUserPage.js, src/ui/users/authority/UserAuthorityPage.js, src/ui/users/detail/DetailUserPage.js, src/ui/users/edit/EditUserPage.js, src/ui/users/list/UserListPage.js
=> EN-1365 DT: Breadcrumbs for User Management are broken

src/ui/fragments/common/FragmentForm.js
=> EN-1367 DT: UX Pattern

src/ui/fragments/list/FragmentListTable.js
=> EN-1367 DT: UX Pattern-delete-fragment

sass/pages/common/PageTreeCompact.scss, sass/pages/config/PageConfigPage.scss, sass/pages/config/ToolbarPageConfig.scss, src/state/page-config/actions.js, src/state/page-config/reducer.js, src/state/page-config/selectors.js, src/ui/pages/common/PageTreeCompact.js, src/ui/pages/config/ContentWidget.js, src/ui/pages/config/PageConfigPage.js, src/ui/pages/config/ToolbarPageConfigContainer.js, test/state/page-config/reducer.test.js
- Fixed widget list overlapping the config grid on small screens
- Fixed case sensitive widget search
- Fixed duplicated key issue (category code / widget code used as key were colliding)
=> En 1394 right hand side overlaps

src/state/users/selectors.js
=> EN-1142-manage-authorization-fix-issue

package-lock.json, package.json
=> update version package @entando/utils and @entando/apimanager

package-lock.json, package.json, src/ui/dashboard/PagesList.js, src/ui/dashboard/PagesListContainer.js
=> changed default sorting and handled content too big in the pages list table

src/locales/en.js, src/locales/it.js, src/state/pages/reducer.js, src/ui/dashboard/PagesList.js, src/ui/pages/common/PageTree.js, src/ui/pages/list/PageListSearchTable.js, src/ui/pages/list/PageTreePage.js, test/state/pages/reducer.test.js, test/ui/pages/common/PageTree.test.js, test/ui/pages/list/PageListSearchTable.test.js
If search returns no results, searchPages will be void array [].
If clearSearch is dispatched, searchPages will be null.
The difference between void array and null is useful switching between PageTree and PageListSearchTable.
=> EN-1415 fix search pages

src/ui/fragments/detail/DetailFragmentPageContainer.js
amend DetailFragmentPageContainer. add gotoRoute function
=> EN-1474-fragment-detail-edit

package-lock.json, src/state/labels/actions.js, src/state/labels/reducer.js, src/state/labels/selectors.js, src/state/labels/types.js, src/state/languages/actions.js, src/ui/labels/add/AddFormContainer.js, src/ui/labels/edit/EditFormContainer.js, src/ui/labels/list/LabelsAndLanguagesPage.js, src/ui/labels/list/LabelsAndLanguagesPageContainer.js, test/state/labels/actions.test.js, test/state/languages/actions.test.js, test/ui/labels/add/AddFormContainer.test.js, test/ui/labels/list/LabelsAndLanguagesPage.test.js, test/ui/labels/list/LabelsAndLanguagesPageContainer.test.js
Hi @nicpuddu @alessioscalici @mcarta-rt @fedelocci ,
Add labels form fixed and labels table pagination fixed.
Could you please take a look?
Thanks!
=> EN-1512-configuration-add-labels-does-not-work

src/ui/dashboard/UserManagement.js, src/ui/dashboard/UxPatterns.js
Reverts entando/app-builder#204
=> Revert "changed button colors"

src/state/page-models/actions.js, src/ui/page-models/common/PageModelFormContainer.js, test/state/page-models/actions.test.js, test/ui/page-models/common/PageModelFormContainer.test.js
fixed also redirect bug when the update or creation would error
=> page models toasts

sass/internal-page/InternalPage.scss, src/locales/en.js, src/locales/it.js, src/ui/internal-page/HomePageLink.js, src/ui/internal-page/HomePageLinkContainer.js, src/ui/internal-page/InternalPage.js, test/ui/internal-page/HomePageLink.test.js, test/ui/internal-page/HomePageLinkContainer.test.js
Hi @nicpuddu @mcarta-rt @alessioscalici @fedelocci ,
Home page link fixed.
Thanks!
=> EN-1364-fix-go-to-name-and-url

src/ui/users/list/UserListMenuActions.js
User list menu action updated, route to user profile edit updated.
IMPORTANT: user profile edit page has not been completed yet.
=> EN-1455 route to user profile edit

src/state/file-browser/actions.js, src/ui/file-browser/list/FilesListTable.js, src/ui/file-browser/list/FilesListTableContainer.js, src/ui/file-browser/utils/downloadFile.js, test/ui/file-browser/list/FilesListTable.test.js, test/ui/file-browser/list/FilesListTableContainer.test.js
add download file and amend test
=> EN-1436 Build download

src/ui/page-models/detail/PageModelPageReferencesTable.js
amend link to edit page in table references pages
=> EN-1476-UX-PageModels

src/locales/en.js, src/locales/it.js, src/state/rootReducer.js, src/state/user-settings/actions.js, src/ui/users/restrictions/RestrictionsForm.js, test/state/user-settings/actions.test.js, test/ui/common/attributes/AttributeListMenuActionsProfile.test.js
success and error messages updated, userSettings state managment updated, fixed AttributeListMenuActionsProfile bug on shallow component
=> EN-1510 Fix user restrictions

src/app-init/router.js, src/locales/en.js, src/locales/it.js, src/ui/data-models/add/AddDataModelPage.js, src/ui/data-models/list/DataModelListPage.js, src/ui/internal-page/InternalPage.js
Hi @nicpuddu @fedelocci @mcarta-rt ,
Data Model renamed to Data Models.
Thanks!
=> EN-1465-data-models-title

src/ui/data-models/list/DataModelListTable.js
Hi @nicpuddu @mcarta-rt @fedelocci ,
Name and type columns swapped.
Thanks!
=> EN-1466-data-models-name-and-type-inverted-in-the-table

__mocks__/api/dataModels.js, src/api/dataModels.js, src/locales/en.js, src/locales/it.js, src/state/data-models/actions.js, src/ui/data-models/common/DataModelListActionsMenu.js, src/ui/data-models/common/DeleteDataModelModal.js, src/ui/data-models/common/DeleteDataModelModalContainer.js, src/ui/data-models/list/DataModelListTable.js, src/ui/data-models/list/DataModelListTableContainer.js, test/api/dataModels.test.js, test/state/data-models/actions.test.js, test/test/mocks/dataModels.js, test/ui/data-models/common/DataModelListActionsMenu.test.js, test/ui/data-models/common/DeleteDataModelModal.test.js, test/ui/data-models/common/DeleteDataModelModalContainer.test.js
Hi @nicpuddu @alessioscalici @mcarta-rt @fedelocci ,
Data Model delete feature added
Thanks!
=> EN-1469-data-models-delete

package-lock.json, src/state/activity-stream/selectors.js
=> fix-activitystream

src/locales/en.js, src/locales/it.js, src/ui/data-models/common/DataModelForm.js
Hi @nicpuddu , @alessioscalici , @fedelocci @mcarta-rt ,
code field help fixed.
Thanks!
=> EN-1560-data-models-code-info-and-requested-param-type-mismatch

src/locales/en.js, src/locales/it.js, src/ui/data-models/common/DataModelForm.js
Hi @nicpuddu , @alessioscalici , @fedelocci @mcarta-rt ,
code field help fixed.
Thanks!
=> [5.0.1] EN-1560-data-models-code-info-and-requested-param-type-mismatch

src/ui/data-models/common/DataModelForm.js
=> [5.0.1] EN-1561-data-models-wrong-label-in-the-form

src/ui/data-models/common/DataModelForm.js
=> EN-1561-data-models-wrong-label-in-the-form

src/state/activity-stream/actions.js, test/state/activity-stream/actions.test.js, test/test/mocks/activityStream.js
=> fix-test-activity-stream

src/ui/page-models/detail/PageModelDetailPage.js, src/ui/page-models/edit/PageModelEditPage.js, test/ui/page-models/detail/PageModelDetailPage.test.js, test/ui/page-models/edit/PageModelEditPage.test.js
add component  DragDropContext to class and amend the test
=> EN-1563→ Page Models → Edit - Blank page on Edit (kebab action)

__mocks__/@entando/router.js, src/state/pages/actions.js, src/state/pages/selectors.js, src/ui/pages/add/PagesAddFormContainer.js, src/ui/pages/common/PageForm.js, test/state/pages/selectors.test.js, test/ui/pages/add/PagesAddFormContainer.test.js
=> [5.0.1] En-1522-501-page-tree-add-from-kebab-action-fix

__mocks__/@entando/router.js, src/state/pages/actions.js, src/state/pages/selectors.js, src/ui/pages/add/PagesAddFormContainer.js, src/ui/pages/common/PageForm.js, test/state/pages/selectors.test.js, test/ui/pages/add/PagesAddFormContainer.test.js
=> En-1522-page-tree-add-from-kebab-action-fix

src/api/profileTypes.js, src/state/attributes/utils.js, src/state/data-types/actions.js, src/state/data-types/reducer.js, src/state/profile-types/actions.js, src/state/profile-types/reducer.js, src/state/profile-types/types.js, src/ui/common/attributes/AttributeListMenuActions.js, src/ui/data-types/common/DataTypeForm.js, src/ui/data-types/edit/EditFormContainer.js, src/ui/profile-types/attributes/DeleteAttributeModal.js, src/ui/profile-types/attributes/DeleteAttributeModalContainer.js, src/ui/profile-types/common/ProfileTypeForm.js, src/ui/profile-types/edit/EditFormContainer.js, test/state/profile-types/actions.test.js, test/state/profile-types/reducer.test.js, test/test/mocks/profileTypes.js, test/ui/data-types/edit/EditFormContainer.test.js
created move attributes actions, created delete profile type attribute modal
=> EN-1570 profileType attributes move and delete actions

package-lock.json, package.json, src/ui/common/attributes/AttributeHypeLongMonoTextSettings.js, src/ui/common/attributes/AttributesDateSettings.js, src/ui/common/attributes/AttributesNumber.js
amend validation isNumber and Normalized Date
=> amend validation isNumber and Normalized Date

src/ui/fragments/common/FragmentForm.js
=> [5.0.1]-EN-1575-coda-validation-fragment

src/ui/fragments/common/FragmentForm.js
=> [MASTER] EN-1575-code-validation-fragment

src/ui/page-models/add/PageModelAddPage.js, test/ui/page-models/add/PageModelAddPage.test.js
amend PageModelAddPage and test
=> [5.0.1] EN-1576-page-models-json-configuration

src/ui/data-models/add/AddDataModelFormContainer.js, src/ui/pages/add/PagesAddPageContainer.js, src/ui/users/add/AddFormContainer.js, src/ui/widgets/common/WidgetFormContainer.js
=> [MASTER] EN-1596-dropdownlist-limited

src/ui/data-models/add/AddDataModelFormContainer.js, src/ui/pages/add/PagesAddPageContainer.js, src/ui/users/add/AddFormContainer.js, src/ui/widgets/common/WidgetFormContainer.js
=> [5.0.1] EN-1596-dropdownlist-limited

src/ui/pages/list/PageTreePage.js
=> [MASTER] EN-1597-rename-page-title

src/ui/pages/common/PageTreeActionMenu.js
amend behavior menu for unpublish and delete
=> [MASTER] EN-1598-disable-not-usable-actions

src/ui/pages/common/PageTreeActionMenu.js
En 1598 disable not usable actions
=> [5.0.1]- EN-1598 disable not usable actions

src/ui/common/form/RenderSelectInput.js
amend RenderSelectedInput add disabled attribute
=> [5.0.1] EN-1599 edit page owner group fix

src/locales/en.js, src/locales/it.js, src/ui/dashboard/DashboardPage.js, src/ui/dashboard/Languages.js, src/ui/dashboard/LanguagesContainer.js, test/ui/dashboard/DashboardPage.test.js, test/ui/dashboard/Languages.test.js, test/ui/dashboard/LanguagesContainer.test.js
=> [5.0.1] EN-1631 Language box Dashboard

src/ui/pages/common/PageForm.js
=> [MASTER] EN-1573

src/ui/pages/common/PageForm.js
En 1573 add page code field validation 5.0.1
=> [5.0.1] En 1573 add page code field validation 

src/ui/pages/edit/PagesEditFormContainer.js
=> [MASTER] EN-1596 dropdownlist

src/ui/pages/common/PageForm.js
added max length to 70 characters for title page
=> [5.0.1] EN-1573

.gitattributes
=> EN-1648 forcing LF line endings on text files

src/state/pages/actions.js, src/state/pages/selectors.js, src/ui/pages/common/PageTreeActionMenu.js, src/ui/pages/config/PageConfigPageContainer.js, src/ui/pages/list/PageTreePageContainer.js
=> [5.0.1] EN-1598-disable not usable action

src/state/pages/actions.js, src/state/pages/selectors.js, src/ui/pages/common/PageTreeActionMenu.js, src/ui/pages/config/PageConfigPageContainer.js, src/ui/pages/list/PageTreePageContainer.js
=> [MASTER] EN-1598 disable not usable action

src/ui/pages/clone/CloneFormContainer.js, src/ui/pages/clone/PagesClonePage.js, test/ui/pages/clone/CloneFormContainer.test.js
=> [5.0.1] EN-1645 clone page 

src/ui/widgets/common/WidgetForm.js, src/ui/widgets/common/WidgetFormContainer.js, src/ui/widgets/edit/EditWidgetFormContainer.js, test/ui/widgets/common/WidgetForm.test.js, test/ui/widgets/common/WidgetFormContainer.test.js, test/ui/widgets/edit/EditWidgetFormContainer.test.js
=> [MASTER] EN-1646 widget add title languages

src/state/pages/actions.js
=> [MASTER]EN-1644 pageConfiguration error publish page

src/state/pages/actions.js
=> [5.0.1] EN-1644 pageConfiguration error publish page

src/state/users/actions.js, src/ui/users/authority/UserAuthorityPage.js, src/ui/users/authority/UserAuthorityTable.js, src/ui/users/common/UserAuthorityPageForm.js, src/ui/users/common/UserAuthorityPageFormContainer.js, test/state/users/actions.test.js, test/ui/users/common/UserAuthorityPageFormContainer.test.js
=> [MASTER] EN-1504 manage auhtorization

src/state/users/actions.js, src/ui/users/authority/UserAuthorityPage.js, src/ui/users/authority/UserAuthorityTable.js, src/ui/users/common/UserAuthorityPageForm.js, src/ui/users/common/UserAuthorityPageFormContainer.js, test/state/users/actions.test.js, test/ui/users/common/UserAuthorityPageFormContainer.test.js
=> [5.0.1] EN-1504 manage authorization

src/ui/widgets/common/WidgetForm.js
remove sort languages and fix select component
=> [MASTER] EN-1647 widget title

src/ui/widgets/common/WidgetForm.js
remove sort languages and fix select component
=> [5.0.1] EN-1647 widget title

src/state/widgets/actions.js, src/ui/widgets/common/WidgetForm.js, src/ui/widgets/common/WidgetFormContainer.js, test/state/widgets/actions.test.js, test/ui/widgets/common/WidgetFormContainer.test.js
- Replaced system languages fields with backoffice languages
- Unit tests
=> [master] EN-1674 Limiting widget form titles to backoffice languages

src/state/users/actions.js, src/ui/users/common/UserAuthorityPageFormContainer.js, test/state/users/actions.test.js
amend the behavior in the contaier and thunk when delete an authority
=> [MASTER] EN-1504 Manager authorizaton users

src/state/profile-types/actions.js, src/ui/profile-types/list/ProfileTypeListTable.js, src/ui/profile-types/list/ProfileTypeListTableContainer.js
=> [MASTER] EN-1712 ProfileTypes loading 

src/state/profile-types/actions.js, src/ui/profile-types/list/ProfileTypeListTable.js, src/ui/profile-types/list/ProfileTypeListTableContainer.js
=> [5.0.1] EN-1712 ProfileTypes loading

src/ui/groups/list/GroupListTableContainer.js
changed sort from code to name
=> [MASTER] EN-1721 sort group list 

src/ui/groups/list/GroupListTableContainer.js
changed sort from code to name
=> [5.0.1] charneg sort group list

src/ui/groups/add/AddGroupPage.js, src/ui/groups/edit/EditGroupPage.js, src/ui/roles/add/AddRolePage.js, src/ui/roles/edit/EditRolePage.js
=> [MASTER] EN-1719 Breadcrumbs roles

src/ui/groups/add/AddGroupPage.js, src/ui/groups/edit/EditGroupPage.js, src/ui/roles/add/AddRolePage.js, src/ui/roles/edit/EditRolePage.js
=> [5.0.1] EN-1719 breadcrumbs roles

src/ui/profile-types/list/ProfileTypeListTableContainer.js
changed sort from code to name
=> [MASTER] EN-1722 sort profile type

src/ui/groups/add/AddFormContainer.js, src/ui/groups/common/GroupForm.js, test/ui/groups/add/AddFormContainer.test.js, test/ui/groups/common/GroupForm.test.js
add behavior when on focus code input
=> [MASTER] EN-1714 Add group code not valid presentation error

src/ui/groups/add/AddFormContainer.js, src/ui/groups/common/GroupForm.js, test/ui/groups/add/AddFormContainer.test.js, test/ui/groups/common/GroupForm.test.js
add behavior when on focus code input
=> [5.0.1] EN-1714 Add group code not valid presentation error

package-lock.json, package.json, src/ui/fragments/list/FragmentSearchForm.js, src/ui/fragments/list/FragmentSearchFormContainer.js, test/ui/fragments/list/FragmentSearchForm.test.js
This PR fixes only Widget type filter.
It also disables Plugin filter until API endpoint is implemented for plugins.
=> EN-1473 Fix fragments filter functionality

src/ui/groups/detail/GroupDetailTabContents.js, src/ui/groups/detail/GroupDetailTabResources.js
show information from group references
=> [V5.0.1] EN-2188 

src/state/user-profile/actions.js, src/ui/groups/detail/GroupDetailTabContents.js, src/ui/groups/detail/GroupDetailTabResources.js, src/ui/users/detail/DetailUserTable.js, test/state/user-profile/actions.test.js
show information from group references
=> [MASTER] EN-2188

src/locales/en.js, src/locales/it.js, src/ui/users/common/UserForm.js, test/ui/users/common/UserForm.test.js
=> [v5.0.1] EN-2182 Username Validation

package-lock.json, package.json
update dependencies esp apimanager 2.2.0
=> apimanager in package.json bumped to 2.2.0

src/api/digital-exchange/plugins.js, test/test/mocks/digital-exchange/plugins.js
https://jira.entando.org/browse/EN-2220
=> EN-2220 Implemented initial mock API for DE plugins.

README.md, config/env.js
https://jira.entando.org/browse/EN-2217
=> EN-2217 created ENABLE_DIGITAL_EXCHANGE_UI env flag 

src/state/data-types/actions.js
fix issue when create Date attribute
=> [v.5.0.3-release] EN-2244 

src/api/digital-exchange/categories.js, src/state/digital-exchange/categories/actions.js, src/state/digital-exchange/categories/reducer.js, src/state/digital-exchange/categories/selectors.js, src/state/digital-exchange/categories/types.js, src/state/rootReducer.js, test/state/digital-exchange/categories/actions.test.js, test/state/digital-exchange/categories/reducer.test.js, test/state/digital-exchange/categories/selectors.test.js, test/test/mocks/digital-exchange/categories.js
1. https://jira.entando.org/browse/EN-2254
2. https://jira.entando.org/browse/EN-2255
=> EN-2254 EN-2255 categories mock API, redux state and tests

src/locales/en.js, src/locales/it.js, src/ui/digital-exchange/CategoryFilter.js, src/ui/digital-exchange/CategoryFilterContainer.js, src/ui/digital-exchange/MarketplaceFilter.js, src/ui/digital-exchange/Sidebar.js, test/ui/digital-exchange/CategoryFilter.test.js
Ready to be reviewed. 
https://jira.entando.org/browse/EN-2252
=> EN-2252 adding sidebar category filter

sass/digital-exchange/RatingFilter.scss, sass/digital-exchange/RatingFilterItem.scss, sass/digital-exchange/common/StarIcon.scss, sass/index.scss, sass/patternfly.scss, src/locales/en.js, src/locales/it.js, src/ui/digital-exchange/RatingFilter.js, src/ui/digital-exchange/RatingFilterContainer.js, src/ui/digital-exchange/RatingFilterItem.js, src/ui/digital-exchange/Sidebar.js, src/ui/digital-exchange/common/StarIcon.js, test/ui/digital-exchange/RatingFilter.test.js, test/ui/digital-exchange/RatingFilterItem.test.js, test/ui/digital-exchange/Sidebar.test.js, test/ui/digital-exchange/common/StarIcon.test.js
https://jira.entando.org/browse/EN-2256
=> EN-2256 sidebar star filter

src/state/digital-exchange/actions.js, src/state/digital-exchange/categories/const.js, src/state/digital-exchange/categories/reducer.js, src/state/digital-exchange/categories/selectors.js, src/state/digital-exchange/components/actions.js, src/state/digital-exchange/components/reducer.js, src/state/digital-exchange/components/selectors.js, src/state/digital-exchange/components/types.js, src/ui/digital-exchange/CategoryFilter.js, src/ui/digital-exchange/CategoryFilterContainer.js, src/ui/digital-exchange/CategoryTabs.js, src/ui/digital-exchange/CategoryTabsContainer.js, src/ui/digital-exchange/MarketplaceFilter.js, src/ui/digital-exchange/MarketplaceFilterContainer.js, src/ui/digital-exchange/RatingFilter.js, src/ui/digital-exchange/RatingFilterContainer.js, src/ui/digital-exchange/Sidebar.js, src/ui/digital-exchange/SidebarContainer.js, test/state/digital-exchange/actions.test.js, test/state/digital-exchange/categories/selectors.test.js, test/state/digital-exchange/components/actions.test.js, test/state/digital-exchange/components/reducer.test.js, test/ui/digital-exchange/CategoryFilter.test.js, test/ui/digital-exchange/CategoryTabs.test.js, test/ui/digital-exchange/MarketplaceFilter.test.js, test/ui/digital-exchange/RatingFilter.test.js
Edit: now it's ready to be reviewed
=> EN-2325 DE multiple filters

test/ui/digital-exchange/common/StarRating.test.js, test/ui/digital-exchange/components/common/ComponentImage.test.js, test/ui/digital-exchange/components/common/ComponentInstallActions.test.js, test/ui/digital-exchange/components/common/ComponentListViewModeSwitcherContainer.test.js, test/ui/digital-exchange/components/list/ComponentListGridView.test.js
https://jira.entando.org/browse/EN-2272
=> EN-2272 Adding tests for DE GridView and related components

src/locales/en.js, src/locales/it.js, src/ui/app/App.js, src/ui/digital-exchange/components/list/ComponentListPage.js, src/ui/digital-exchange/components/list/ComponentListPageDisabled.js, src/ui/internal-page/InternalPage.js, test/ui/digital-exchange/components/list/ComponentListPageDisabled.test.js
https://jira.entando.org/browse/EN-2217
=> EN-2217 utilizing ENABLE_DIGITAL_EXCHANGE_UI env flag.

sass/digital-exchange/components/ComponentList.scss, sass/patternfly.scss, src/ui/digital-exchange/components/common/ComponentInstallActions.js, src/ui/digital-exchange/components/list/ComponentListGridView.js, src/ui/digital-exchange/components/list/ComponentListListView.js, test/ui/digital-exchange/components/list/ComponentListListView.test.js
Ready to be reviewed.
https://jira.entando.org/browse/EN-2334
=> EN-2334 Implementing Components List View.

sass/digital-exchange/components/ComponentList.scss
https://jira.entando.org/browse/EN-2428
=> EN-2428 - fixing styling issue that prevented install button click.

package-lock.json, package.json, src/state/store.js
https://jira.entando.org/browse/EN-2326
=> EN-2326 persisting locale info into local storage.

package-lock.json, package.json, src/app-init/apiManager.js
frontend-libraries/@entando-utils dependency update to enable multifilter ‘OR’ in DE
=> EN-2411 enable multifilter OR

sass/pages/config/ToolbarPageConfig.scss, sass/patternfly.scss, src/ui/pages/config/PageConfigPage.js, src/ui/pages/config/ToolbarPageConfig.js, src/ui/pages/config/ToolbarPageConfigContainer.js, test/ui/pages/config/ToolbarPageConfigContaier.test.js
included flickering issue when scrolling down, added test to omit getboundingcoords
=> EN-2309	fixing scroll using mouse wheel on sidebar

sass/pages/config/PageConfigPage.scss
fix on disabled draggable item at the bottom of the toolbar view - bug spotted by Simone
=> EN-2309 - page config toolbar scrolling drag item fix

README.md, config/env.js
https://jira.entando.org/browse/EN-2496
=> EN-2496 - Adding CMS_UI_ENABLED flag

src/app-init/apiManager.js
this is a fix for plugin store config that shows a callback error when you install jpkiebpm plugin
=> EN-2411 - dependency update - plugins store config change to callbacks

src/state/page-config/actions.js, test/state/page-config/actions.test.js
Fixes EN6-132 issue: Cannot publish twice from page configuration
=> EN6-132 Update selected page status when page widgets change

src/ui/internal-page/InternalPage.js
Removed integrations item from menu
=> En6 154 integrations menu

src/index.js, src/ui/common/form/LoadableCodeMirror.js
This is to add search feature for most code editors (specifically using 'CodeMirror' component). I only activated existing addons (found it here, https://codemirror.net/demo/search.html).
=> EN6-145 search box for code editors

src/ui/file-browser/upload/UploadFileBrowserForm.js
literally just remove acceptfile prop. nothing more, nothing less. :D
=> EN6-146 remove file browse filter in file browser for upload

src/ui/pages/config/PageConfigPage.js, src/ui/pages/config/PageConfigPageContainer.js
Fix on loading config when browsing via page list on right toolbar
=> EN6-153 Page Config loading on changing url (params)

sass/pages/config/PageConfigPage.scss, src/ui/pages/config/PageConfigPage.js, src/ui/pages/config/ToolbarPageConfig.js
Re-implement scrolling in PageConfigPage to improve UX.
=> EN6-149 Re-implement scrolling in PageConfigPage

src/ui/internal-page/InternalPage.js
Quick fix by adding missing key attribute
=> EN6-177 key requirement error fix for integrated apps

package-lock.json, package.json
in order to use the mobile/tablet compatible login screen from @entando/pages
=> EN6-171 entando pages updated to 2.2

src/state/pages/reducer.js, src/state/pages/selectors.js
also added removal of page item in search result list after prompting to remove page
=> ENG-58 page delete option disabled fix in page search results

nginx.conf
This commit will implement a gzip configuration for nginx inside docker image
=> ENG-73 bundle size

src/state/page-config/actions.js, src/state/page-config/selectors.js, src/ui/pages/config/PageConfigGrid.js, src/ui/pages/config/PageConfigGridCol.js, src/ui/pages/config/PageConfigGridRow.js, src/ui/pages/config/WidgetFrame.js, test/state/page-config/actions.test.js, test/ui/pages/config/WidgetFrame.test.js
When user navigated to Page Configuration of a specific page and then clicks on settings button (three dots) of a widget then:
- Shows `settings`, `details` and `delete` actions in Kebab button
=> ENG-81 Kebab button actions

src/locales/en.js, src/locales/it.js, src/state/digital-exchange/components/actions.js, src/ui/digital-exchange/DigitalExchangeFilter.js, src/ui/digital-exchange/components/list/ComponentList.js, test/state/digital-exchange/components/actions.test.js
- Text visual feedbacks are provided
=> ENG-30 provide feedback if DEs or corresponding components are not presented

package-lock.json, package.json, src/app-init/apiManager.js, src/auth/default/DefaultAuthProvider.js, src/ui/app/App.js
made for both default and keycloak auth
=> ENG-33 redirect after login

package-lock.json, package.json, src/helpers/microfrontends.js, src/helpers/useScript.js, src/helpers/useScripts.js, src/locales/en.js, src/locales/it.js, src/locales/pt.js, src/ui/widgets/config/WidgetConfigForm.js, src/ui/widgets/config/WidgetConfigMfeWrapper.js, src/ui/widgets/config/WidgetConfigPage.js, src/ui/widgets/config/WidgetConfigPageContainer.js, src/ui/widgets/config/useScript.js, test/ui/widgets/config/WidgetConfigMfeWrapper.test.js
=> ENG-108 widget config mfe

config/env.js, package-lock.json, package.json
Fixes issue on paths with improper protocols.
=> ENG-109 Use isURL validator to validate DOMAIN env variable

src/helpers/resourcesHookFactory.js, src/helpers/useScript.js, src/helpers/useScripts.js, src/helpers/useStylesheet.js, src/helpers/useStylesheets.js, src/ui/widgets/config/WidgetConfigMfeWrapper.js
note: shadow dom support is not included as it should not be useful for widget config MFE
=> Eng 108 widget config mfe

sass/digital-exchange/settings/SettingsList.scss, src/locales/en.js, src/locales/it.js, src/ui/internal-page/InternalPage.js, src/ui/plugins/PluginsListItem.js, src/ui/plugins/PluginsPage.js, src/ui/plugins/PluginsPageContainer.js, test/ui/plugins/PluginsPageContainer.test.js
Currently blocked by `ENG-104`
=> ENG-105 implement UI and basic functionality for Installed Plugins page

package-lock.json, package.json
to take effect on copyright auto-generated year in login page
=> ENG-189 @entando/pages version bump up

sass/internal-page/InternalPage.scss, src/ui/internal-page/HomePageLinkContainer.js, src/ui/internal-page/InternalPage.js, src/ui/internal-page/LanguageSelect.js, src/ui/internal-page/LanguageSelectContainer.js, test/ui/internal-page/LanguageSelect.test.js, test/ui/internal-page/LanguageSelectContainer.test.js
* Adds language select interface to the top-right header menu
* Fixes the language selection issue
=> ENG-91 Implement LanguageSelect

src/locales/en.js, src/locales/it.js, src/locales/pt.js, src/ui/common/form/RenderFileInput.js, src/ui/file-browser/common/FileButtonsGroup.js, src/ui/file-browser/upload/UploadFileBrowserForm.js, src/ui/file-browser/upload/UploadFileBrowserFormContainer.js, src/ui/file-browser/upload/UploadFileBrowserPage.js, test/ui/file-browser/upload/UploadFileBrowserFormContainer.test.js
This PR enables:
- to upload multiple files per upload
does not enable:
- uploading folders too along with single files
=> ENG-224 let user to upload multiple files

src/state/page-config/actions.js
- This PR fixes widget duplication when being dragged/dropped
=> ENG-158 await for delete and put only then

package-lock.json, package.json
this is to solidify the regression fix on bad request 400 error catch
=> ENG-409 apimanager patch version bump

src/ui/widgets/config/WidgetConfigPage.js
CMS widget config on user filters
=> trigger JX build for Entando-cms 0.2.73

src/ui/widgets/config/WidgetConfigPage.js
This reverts commit b8364f0eac1e996cfda1b2fb9616d72f4baf8794.
=> Revert "trigger JX build for entando-cms 0.2.73"

package.json, src/ui/dashboard/LanguagesContainer.js
- Used for triggering new build for cms
- Use fixed `utils` package
=> ENG-640 fix dates

src/ui/app/App.js, src/ui/internal-page/BrandMenuContainer.js
- Fix auth problem for plugins
- Add `key` to `LinkItems` as they were placed in Array and React asks for keys now :)
=> ENG-680 fix plugin auth error

package-lock.json, package.json, src/ui/app/App.js, src/ui/app/PageNotFound.js, src/ui/app/PageNotFoundContainer.js, test/ui/app/App.test.js
- added container for page not found page plus updated entando pages
=> ENG-643 Align Error Pages

src/ui/dashboard/DashboardPage.js, src/ui/file-browser/utils/downloadFile.js
- also includes small bugfix for File download that has no extension
=> ENG-686 add status card for contents on dashboard

config/env.js, src/helpers/versions.js, src/ui/internal-page/BrandMenuContainer.js, src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
this does not show version 6.2 but when package.json will now bump into 6.2 then so will be the version shown in the title
=> ENG-767 App builder title’s version using package.json version

src/ui/dashboard/PageStatus.js, src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
- Includes link for dashboard on brand menu
=> ENG-874 add new chart colors

sass/patternfly.scss
* Fixes css precedence issues when integrating cms into appbuilder
=> ENG-857 Make primary button color styles important

src/ui/pages/common/SeoInfo.js
solution is to unmount the tab whenever it switches to inactive to force-render the switch values
=> ENG-773 fix on switch indetermined state when a field value from different tab changes

src/ui/widgets/detail/DetailWidgetElement.js
* Fixes formatting of dropdown kebab items
* Fixes the URL of the items
=> ENG-1039 Fix row action dropdown of widget details

src/helpers/entities.js, src/locales/en.js, src/locales/it.js, src/locales/pt.js, src/state/users/actions.js, src/ui/profile-types/common/ProfileTypeReferenceStatus.js, src/ui/user-profile/common/UserProfileForm.js, src/ui/user-profile/edit/EditUserProfileFormContainer.js, src/ui/users/add/AddFormContainer.js, src/ui/users/common/UserForm.js, test/ui/users/add/AddFormContainer.test.js, test/ui/users/common/UserForm.test.js
PR Includes:
-> Save and Edit profile button when adding new user
-> When editing the profile of a user, ability to change profile type too
-> Adding a Profile Types reference status on profile types screen
-> Edge case fixes for null values on some places
-> Fixed tests
=> ENG-977 fix user and profile related issues and add new features

src/ui/widgets/common/WidgetForm.js
=> ENG-722 remove unwanted button from add widget screen

src/ui/common/attributes/AttributeRole.js, src/ui/common/form/RoleSelectRenderer.js
an issue resolved when such case that all roles are assigned but it shows no selection for deletion of roles (also implemented in content types awhile ago)
=> ENG-1495 issue on all roles that are already assigned (profile types)

sass/pages/common/MultiSelectRenderer.scss
resolution from @fedelocci (see https://entando.slack.com/archives/C9244SALA/p1605891079079400)
=> Add button alignment to dropdown - multiselect field component

src/state/page-config/actions.js
Fetch only publish page config if page isn't unpublished to avoid errors
=> ENG-1554 Fix page config fetching logic

src/state/store.js, test/state/store.test.js
* Fixes issues related to content displaying old values
* Reduces the size of the stored redux state in localStorage
=> ENG-1623 Reimplement local storage state persistence logic

package-lock.json, package.json
Fixes FieldArray issue when pushing new fields (https://github.com/redux-form/redux-form/issues/4439)
=> ENG-1633 Update redux-form

src/ui/component-repository/components/item/install-controls/ComponentInstallActionsContainer.js
Pass required callback in recheck props in ComponentInstallActionsContainer > mapDispatchToProps
=> ENG-1643 Fix error caused by rechecking install status

src/ui/app-tour/AppTour.js
=> ENG-1593 Increase scroll lock threshold

Dockerfile
Reverts entando/app-builder#1025
=> Revert "Update dockerfile to patch security in default builds and to manually…"

package-lock.json, src/ui/dashboard/PagesList.js
included package-lock.json update for datatable version update
=> ENG-2060 resolve dashboard pagelist error

src/auth/keycloak/KeycloakProviderContainer.js, src/state/app-tour/reducer.js, src/ui/common/form/RenderDropdownTypeaheadInput.js, test/state/app-tour/reducer.test.js
- Fetch wizard enabled value when logging in
- Fix reducer for app tour
- Fix new component not having app tour step class
- Fix test
=> ENG-2177 fix tutorial

src/ui/widgets/common/IconLibrary.js, src/ui/widgets/common/WidgetForm.js, src/ui/widgets/edit/EditWidgetFormContainer.js, test/ui/widgets/edit/EditWidgetFormContainer.test.js
* Makes widget parameter fields disabled if editing a user widget
* Fixes some console warnings
=> ENG-2374 Make parameter fields disabled if editing a user widget

src/api/component-repository/components.js, src/locales/en.js, src/locales/it.js, src/locales/pt.js, src/state/component-repository/components/actions.js, test/test/mocks/component-repository/components.js
=> ENG-2376: properly handling poll response of the new API

sass/internal-page/InternalPage.scss, sass/patternfly.scss, src/locales/en.js, src/locales/it.js, src/locales/pt.js, src/ui/about/AboutInfoModal.js, src/ui/about/AboutInfoModalContainer.js, src/ui/internal-page/InfoMenu.js, src/ui/internal-page/InternalPage.js, src/ui/internal-page/VerticalMenuContainer.js
* Re-implements about info as modal instead of page
* Re-implements vertical nav layout and behavior
=> ENG-2252 Improve UX of app-builder menu

sass/pages/config/WidgetGroupingListItem.scss
Some icons are black, we need to make them grey just as other icons are
=> ENG-2364 fix svg color

sass/internal-page/InternalPage.scss, src/helpers/useLocalStorage.js, src/ui/internal-page/VerticalMenuContainer.js
Fix styles, persist side nav expand/collapse state locally (via localStorage)
=> ENG-2252 Add expand/collapse button to bottom of side nav

Dockerfile, package-lock.json, package.json
Update Entando version to 6.4.0
=> ENG-2603 update entando version
